export const userSelect = {
  id: 1,
  username: 1,
  displayName: 1,
  email: 1,
  emailConfirmed: 1,
  firstName: 1,
  lastName: 1,
  birthDate: 1,
  location: 1,
  salary: 1,
  biography: 1,
  websiteLink: 1,
  photoUrl: 1,
  coverUrl: 1,
  createdAt: 1,
  updatedAt: 1,
  userRoles: 1,
};

export const userDetailSelect = {
  id: 1,
  displayName: 1,
  username: 1,
  password: 1,
  email: 1,
  emailConfirmed: 1,
  firstName: 1,
  lastName: 1,
  birthDate: 1,
  salary: 1,
  photoUrl: 1,
  coverUrl: 1,
  themeSource: 1,
  themeStyle: 1,
  createdAt: 1,
  updatedAt: 1,
  securityStamp: 1,
  userRoles: 1,
};
