export const userSelect = {
  _id: 0,
  id: '$_id',
  displayName: 1,
  email: 1,
  emailConfirmed: 1,
  firstName: 1,
  lastName: 1,
  photoUrl: 1,
  createdAt: 1,
  updatedAt: 1,
  userRoles: 1,
  postcode: 1,
};

export const userDetailSelect = {
  _id: 0,
  id: '$_id',
  displayName: 1,
  password: 1,
  email: 1,
  emailConfirmed: 1,
  firstName: 1,
  lastName: 1,
  photoUrl: 1,
  createdAt: 1,
  updatedAt: 1,
  securityStamp: 1,
  userRoles: 1,
  postcode: 1,
};
